#!/usr/bin/env bash
set -euo pipefail

repo_root="$(CDPATH= cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
shared_root="${repo_root}/shared/devfoundry"
user_config_root="${XDG_CONFIG_HOME:-${HOME}/.config}/devfoundry"
user_share_root="${XDG_DATA_HOME:-${HOME}/.local/share}/devfoundry"
git_config_root="${XDG_CONFIG_HOME:-${HOME}/.config}/git"
system_root="${DEVFOUNDRY_SYSTEM_HOME:-/etc/devfoundry}"
force_user_shared="${1:-}"

copy_file() {
  local source_file="$1"
  local target_file="$2"

  mkdir -p "$(dirname "${target_file}")"
  cp "${source_file}" "${target_file}"
}

write_user_git_config() {
  mkdir -p "${git_config_root}"

  cat > "${git_config_root}/config" <<EOF
# Generated by devfoundry.
# Shared Git defaults for user-owned mode.

[include]
    path = ${user_share_root}/git/base.gitconfig

[include]
    path = ${user_share_root}/git/aliases.gitconfig
EOF
}

remove_legacy_user_shared_files() {
  rm -f \
    "${user_config_root}/git/base.gitconfig" \
    "${user_config_root}/git/aliases.gitconfig" \
    "${user_config_root}/zsh/profile.zsh" \
    "${user_config_root}/zsh/rc.zsh" \
    "${user_config_root}/zsh/aliases.zsh" \
    "${user_config_root}/zsh/load-profile.zsh" \
    "${user_config_root}/zsh/load-rc.zsh" \
    "${user_config_root}/zsh/p10k.zsh" \
    "${user_config_root}/zsh/plugins.txt"
}

system_shared_present=false

if [[ -r "${system_root}/git/base.gitconfig" && -r "${system_root}/zsh/load-rc.zsh" ]]; then
  system_shared_present=true
fi

if [[ "${force_user_shared}" == "--force-user-shared" ]]; then
  system_shared_present=false
fi

if [[ "${system_shared_present}" == true ]]; then
  remove_legacy_user_shared_files
  echo "system devfoundry defaults detected at ${system_root}; skipping shared user sync"
  exit 0
fi

copy_file "${shared_root}/git/base.gitconfig" "${user_share_root}/git/base.gitconfig"
copy_file "${shared_root}/git/aliases.gitconfig" "${user_share_root}/git/aliases.gitconfig"
copy_file "${shared_root}/zsh/profile.zsh" "${user_share_root}/zsh/profile.zsh"
copy_file "${shared_root}/zsh/rc.zsh" "${user_share_root}/zsh/rc.zsh"
copy_file "${shared_root}/zsh/aliases.zsh" "${user_share_root}/zsh/aliases.zsh"
copy_file "${shared_root}/zsh/load-profile.zsh" "${user_share_root}/zsh/load-profile.zsh"
copy_file "${shared_root}/zsh/load-rc.zsh" "${user_share_root}/zsh/load-rc.zsh"
copy_file "${shared_root}/zsh/p10k.zsh" "${user_share_root}/zsh/p10k.zsh"
copy_file "${shared_root}/zsh/plugins.txt" "${user_share_root}/zsh/plugins.txt"

remove_legacy_user_shared_files
write_user_git_config
